name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYTHONHASHSEED: 42
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Container smoke tests
        run: |
          docker run -d --name triage_test -p 8080:8000 ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          sleep 5
          curl --fail http://localhost:8080/health
          curl --fail -H "Content-Type: application/json" -d '{"age":0.02,"sex":-0.04,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' http://localhost:8080/predict
          docker stop triage_test
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }} — see CHANGELOG.md and artifacts/metrics.json
